[versions]
agp = "8.9.3"
kotlin = "2.1.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"
appcompat = "1.7.1"
navigation = "2.9.5"
coroutines = "1.10.1"
paging = "3.3.6"
foundation = "1.8.3"
activity = "1.11.0"
constraintlayout = "2.2.1"
workManager = "2.11.0"
room = "2.8.3"
ksp = "2.1.10-1.0.31"
coil = "2.7.0"
startup = "1.2.0"
accompanistWebview = "0.30.1"
media3 = "1.8.0"
datastore = "1.1.7"
hilt = "2.54"
hiltExt = "1.3.0"
hiltNavigationCompose = "1.3.0"
timber = "5.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
# Lifecycle
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycleRuntimeKtx" }
# Compose
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "kotlin" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
# paging
compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }

# Nagivation
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
# Material
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
# WorkManager
androidx-workmanager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
# Room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
# startUp
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
# retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
retrofitGson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "2.9.0" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.12.0" }
okhttpLoggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "4.12.0" }
# coil
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
# webview
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistWebview" }
# media
androix-media = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androix-media-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
# dataStore
data-store = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
data-store-proto = { group = "androidx.datastore", name = "datastore-proto", version.ref = "datastore" }
data-store-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
# hilt
hilt-android-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# other
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[bundles]
media = [
    "androix-media",
    "androix-media-ui",
]
compose = [
    "compose-bom",
    "compose-activity",
    "compose-runtime",
    "compose-navigation",
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
    "compose-foundation",
    "compose-foundation-layout",
    "compose-material3",
    "compose-material",
    "compose-material-icons-core",
    "compose-material-icons-extended",
    "androidx-lifecycle-viewmodel-compose",
]
lifecycle = [
    "androidx-lifecycle-livedata-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-viewmodel-savedstate",
]
paging = [
    "compose-paging",
    "paging-runtime",
    "room-paging",
]
room = [
    "room-ktx",
    "room-runtime"
]
datastore = [
    "data-store",
    "data-store-preferences",
]
hilt = [
    "hilt-android-core",
    "hilt-android-testing",
    "hilt-navigation-compose",
]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
